(cl:in-package :cl-bodge.text)

(define-system-function build-sdf-font ge.gx:graphics-system (name)
  (let* ((font-atlas-name (ge.rsc:sdf-font-metrics-resource-name name))
         (image-name (fad:merge-pathnames-as-file (fad:pathname-directory-pathname font-atlas-name)
                                                  "image"))
         (font-chunk (load-resource font-atlas-name))
         (atlas-image (load-resource image-name))
         (glyphs (loop for g in (ge.rsc:font-atlas-resource-glyphs font-chunk)
                       collect (make-glyph (code-char (ge.rsc:glyph-metrics-resource-character g))
                                           (ge.rsc:glyph-metrics-resource-origin g)
                                           (ge.rsc:glyph-metrics-resource-bounding-box g)
                                           (ge.rsc:glyph-metrics-resource-advance-width g)
                                           (ge.rsc:glyph-metrics-resource-kernings g)))))
    (bake-font atlas-image glyphs
               (ge.rsc:font-atlas-resource-ascender font-chunk)
               (- (ge.rsc:font-atlas-resource-descender font-chunk))
               (ge.rsc:font-atlas-resource-line-gap font-chunk))))
